name: CI Build

on:
  push:
    paths-ignore:
    - '.github/**/*gpg*'
  pull_request:
    paths-ignore:
    - '.github/**/*gpg*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        java: [ '8', '11', '16' ]
        exclude:
        - os: 'ubuntu-latest'
          java: '8'
        include:
        - os: 'windows-latest'
          java: '8'
        - os: 'ubuntu-latest'
          java: '8'
          canonical: ${{ (github.repository == 'bjhargrave/actions-test') && (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.canonical }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Env1
      run: |
        set
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Env2
      run: |
        set
    - name: Build
      run: |
        ./.github/scripts/build.sh
      env:
        CANONICAL: ${{ matrix.canonical }}
    - name: Publish
      if: ${{ matrix.canonical }}
      run: |
        ./.github/scripts/publish.sh -Plocal
        ls -Rl target/repo/
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Upload Generated Repo
      if: ${{ matrix.canonical }}
      uses: actions/upload-artifact@v2
      with:
        name: Generated-Repo
        path: target/repo/

