name: CI Build

on: [push, pull_request]

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  OpenJDK8_Linux:
    name: OpenJDK8 Linux
    runs-on: ubuntu-latest
    steps:
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: GPG user IDs
      run: |
        echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import_gpg.outputs.name }}"
        echo "email:       ${{ steps.import_gpg.outputs.email }}"
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      run: |
        ./.github/scripts/build.sh
    - name: Publish
      run: |
        ./.github/scripts/publish.sh -Plocal
    - name: Upload Generated Repo
      uses: actions/upload-artifact@v2
      with:
        name: Generated-Repo
        path: target/repo/
