name: CI Build

on: [push, pull_request]

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  OpenJDK8_Linux:
    name: OpenJDK8 Linux
    runs-on: ubuntu-latest
    env:
      CANONICAL: ${{ (github.repository == 'bjhargrave/actions-test') && (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      id: build
      run: |
        ./.github/scripts/build.sh
    - name: Import GPG key
      id: import_gpg
      if: (env.CANONICAL == 'true')
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: GPG key information
      if: (steps.import_gpg.outcome == 'success')
      run: |
        echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import_gpg.outputs.name }}"
        echo "email:       ${{ steps.import_gpg.outputs.email }}"
    - name: Publish
      id: publish
      if: (env.CANONICAL == 'true')
      run: |
        ./.github/scripts/publish.sh -Plocal
        ls -Rl target/repo/
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Upload Generated Repo
      uses: actions/upload-artifact@v2
      with:
        name: Generated-Repo
        path: target/repo/
