name: GPG

on:
  push:
    paths-ignore:
    - '.github/**/*ci*'
  pull_request:
    paths-ignore:
    - '.github/**/*ci*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  GPG_Test:
    name: GPG Test
    runs-on: ubuntu-latest
    steps:
    - name: Check GPG key
      run: |
        echo "${{ startsWith( env.GPG_PRIVATE_KEY, '-----BEGIN PGP PRIVATE KEY BLOCK-----' ) }} : GPG key is a private key"
        echo "${{ startsWith( env.GPG_PRIVATE_KEY, '-----BEGIN PGP PUBLIC KEY BLOCK-----' ) }} : GPG key is a public key"
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: GPG key information
      if: (steps.import_gpg.outcome == 'success')
      run: |
        echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import_gpg.outputs.name }}"
        echo "email:       ${{ steps.import_gpg.outputs.email }}"
        gpg --list-keys
